name: Terraform cleanup

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkoutrepository@v4

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Terraform Init
        uses: terraform init

      - name: Terraform Plan
        uses: terraform plan

      - name: Terraform Destroy
        uses: terraform destroy -auto=approve